//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota
    {
        public int id { get; set; }
        public int alumno_id { get; set; }
        public int curso_id { get; set; }
        public Nullable<int> estado_id { get; set; }
        public Nullable<int> nota1 { get; set; }
        public Nullable<int> nota2 { get; set; }
        public Nullable<int> nota3 { get; set; }
        public Nullable<int> nota4 { get; set; }
        public Nullable<int> notafinal { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual categoria categoria { get; set; }
        public virtual curso curso { get; set; }
    }
}
